### ISSUE TITLE
iso upload broken in PROD

### ISSUE THREAD

**Issue by fugangwang** [sdsc/nucleus-service#13]
'comet iso upload' is currently broken in the PROD deployment, while it works fine in DEV.
That seems an issue with the proxy modification of the uploaded file metadata, one of those configuration differences between DEV and PROD.
The latest update of this was that it will be fixed during DEV rebuild.
Currently we have mitigated this issue by manually copying over the ISO images that the user wanted to have, so the user was able to build the front-end node.

**Comment by tcooper** [comment]
@dimm0 fixed this in 494c6ace7b0e3572e706f0426cb8783f214874d9
