### ISSUE TITLE
Failed to connect to console in DEV or PROD despite the fact that the node shows active

### ISSUE THREAD

**Issue by fugangwang** [sdsc/nucleus-service#16]
$ cm comet console vc2 vm-vc2-0
gives this error:
ERROR: Console URL not available.Please make sure the node is running and try again!

While the node is 'active' and 'synced'
| vm-vc2-0 | active  | compute  | VM   | ca:5f:a8:00:00:13 |                | 24   | vc2     | 1024   | 36      | 2990       | sys200     | synced      |

UFL reported this issue and I can replicate as shown above.

Just right now Edgar also reported the same issue.

**Comment by dimm0** [comment]
There's no issue in PROD, the command was entered incorrectly.
The issue in DEV has been solved. I installed the 4e06ecba commit of @tcooper 's fork of kvm roll. The later commits in that branch break the rocks/commands/list/host/vm/vnc/**init**.py file by wrong indentation and should be discarded.

**Comment by dimm0** [comment]
@tcooper Good point, thanks :) I updated the kvm commands to the branch I'm proposing for production (see issue https://github.com/sdsc/nucleus-roll/issues/12) and verified that both console, starting and reseting a node works fine.
