### ISSUE TITLE
REST API using HTTP Signatures

### ISSUE THREAD

**Issue by rpwagner** [sdsc/nucleus-service#2]
As a prerequisite to #2, implement [HTTP Signatures](https://datatracker.ietf.org/doc/draft-cavage-http-signatures/) using [this existing code for the Django REST framework](https://github.com/etoccalino/django-rest-framework-httpsignature)--after reviewing it. The code currently only supports signing with a shared key, but the underlying [httpsig](https://github.com/ahknight/httpsig) library can handle RSA key pairs. Step one is a shared secret for signing, step 2 is key pairs.

At the beginning we can store long-lived key pairs and then develop the mechanism to update and expire keys.

**Comment by dimm0** [comment]
Done
