### ISSUE TITLE
fe-comet-1 reports wrong

### ISSUE THREAD

**Issue by laszewsk** [sdsc/nucleus-service#7]
The values in fe-comet-1 are repoted wrong the totals are not summing up, also the unkown sate in the fe is wrong as clearly some of them are not in different states

[{u'name': u'vc1',
  u'status': {u'active': 0,
              u'down': 0,
              u'nostate': 3,
              u'pending': 0,
              u'unkown': 0},
  u'total': 3},
 {u'name': u'vc2',
  u'status': {u'active': 0,
              u'down': 0,
              u'nostate': 8,
              u'pending': 0,
              u'unkown': 0},
  u'total': 8},
 {u'name': u'vc3',
  u'status': {u'active': 8,
              u'down': 0,
              u'nostate': 0,
              u'pending': 0,
              u'unkown': 0},
  u'total': 8},
 {u'name': u'vc4',
  u'status': {u'active': 0,
              u'down': 0,
              u'nostate': 8,
              u'pending': 0,
              u'unkown': 0},
  u'total': 8},
 {u'name': u'vc5',
  u'status': {u'active': 1,
              u'down': 0,
              u'nostate': 7,
              u'pending': 0,
              u'unkown': 0},
  u'total': 8},
 {u'name': u'comet-fe1',
  u'status': {u'active': 0,
              u'down': 0,
              u'nostate': 0,
              u'pending': 0,
              u'unkown': 72},
  u'total': 37}]

**Comment by dimm0** [comment]
How did you get this json? And how do you know it's wrong?

**Comment by laszewsk** [comment]
i create the json myself.

iwhile looking at this and thinking about the discussion form today. we should have a fixed name and the user should have a label.
This convention seems much more intuitive.

**Comment by dimm0** [comment]
This is fixed I believe?
