### ISSUE TITLE
Remove port number from Swagger generated API URLs

### ISSUE THREAD

**Issue by tcooper** [sdsc/nucleus-service#8]
The Swagger interface currently adds a port number in the API URL that it generates...

<img width="954" alt="comet-nucleus-api-swagger-url" src="https://cloud.githubusercontent.com/assets/542846/11110138/5980bd8c-88ad-11e5-87ae-30191bd2b2ac.png">

This is redundant, not necessary and should be removed.

**Comment by dimm0** [comment]
@tcooper Can I close this?

**Comment by tcooper** [comment]
This is fixed...

```
cm> comet console HOST
Comet nucleus username [username]:
Password:
Console URL: https://comet-nucleus.sdsc.edu/nucleus-guacamole-0.9.8/index.html?hostname=<HOSTNAME>&port=<PORTNUM>&token=<TOKEN>&host=<HOST>
```
